{"timestamp":"2025-07-11T11:32:47.032391","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T11:32:47.032962","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/main.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T11:32:47.417875Z","level":"error","event":"WARNING: Using incubator modules: jdk.incubator.vector","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-11T11:32:48.910829Z","level":"error","event":"25/07/11 11:32:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-11T11:32:49.130620Z","level":"error","event":"Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-11T11:32:49.131347Z","level":"error","event":"Setting default log level to \"WARN\".","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-11T11:32:49.131820Z","level":"error","event":"To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-11T11:32:56.072392Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:32:56.072823Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:32:56.073097Z","level":"info","event":"Current task name:data_mino","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:32:56.073487Z","level":"info","event":"Dag name:etl_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:33:11.565219","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"EndpointConnectionError","exc_value":"Could not connect to the endpoint URL: \"http://localhost:9001/browser/weather-data\"","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/my_minio/upload.py","lineno":26,"name":"upload_to_minio"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":569,"name":"_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1005,"name":"_make_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1029,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":119,"name":"make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":200,"name":"_send_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":360,"name":"_needs_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":412,"name":"emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":256,"name":"emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":239,"name":"_emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":207,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":284,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":320,"name":"_should_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":363,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":247,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":416,"name":"_check_caught_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":279,"name":"_do_get_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":383,"name":"_send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py","lineno":493,"name":"send"}]},{"exc_type":"EndpointConnectionError","exc_value":"Could not connect to the endpoint URL: \"http://localhost:9001/browser/weather-data\"","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/my_minio/upload.py","lineno":24,"name":"upload_to_minio"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":569,"name":"_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1005,"name":"_make_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1029,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":119,"name":"make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":200,"name":"_send_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":360,"name":"_needs_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":412,"name":"emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":256,"name":"emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py","lineno":239,"name":"_emit"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":207,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":284,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":320,"name":"_should_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":363,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":247,"name":"__call__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/retryhandler.py","lineno":416,"name":"_check_caught_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":279,"name":"_do_get_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py","lineno":383,"name":"_send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py","lineno":493,"name":"send"}]},{"exc_type":"NewConnectionError","exc_value":"<botocore.awsrequest.AWSHTTPConnection object at 0x7f3b383de450>: Failed to establish a new connection: [Errno 111] Connection refused","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/httpsession.py","lineno":464,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py","lineno":96,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":445,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py","lineno":123,"name":"_send_output"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/awsrequest.py","lineno":223,"name":"send"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":276,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":213,"name":"_new_conn"}]},{"exc_type":"ConnectionRefusedError","exc_value":"[Errno 111] Connection refused","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":85,"name":"create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":73,"name":"create_connection"}]}]}
{"timestamp":"2025-07-11T11:33:11.603797Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:33:11.604369Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:33:11.604780Z","level":"info","event":"Task:<Task(PythonOperator): data_mino>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T11:33:11.605111Z","level":"info","event":"Failure caused by Could not connect to the endpoint URL: \"http://localhost:9001/browser/weather-data\"","chan":"stdout","logger":"task"}
